name: my_project
description: A new Dart project.
version: 1.0.0

environment:
  sdk: "^3.4.0"

dependencies:
  characters: ^1.2.0
  http: ^1.2.1
  json_annotation: ^4.9.0
dev_dependencies:
  # build_runner: ^2.4.11
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
